### ISSUE TITLE
Intensity dial has misspelled OSC path: /eos/wheel/course/Intens

### ISSUE THREAD

**Issue by n9yty** [sstaub/eosstreamdeckplus#4]
Path should be: /eos/wheel/coarse/Intens

Looks like changing the variable $(internal:custom_enc_1_res) from 'course' to 'coarse' fixes it

I believe this  is the experimental/eos_v3.companionconfig file, I have to double check, sorry, but I loaded it up some days ago and just today received my hardware and started testing.

**Comment by sstaub** [comment]
Thank you for that advice, there are many typos like this. It should work now in the latest release.
